#coding:utf-8

#数据库配置
test_db: '{
  "host":"192.168.3.216",
  "user":"root",
  "password":"66ifuel",
  "db":"charging",
  "port":"3306",
  "charset":"utf8"}'
#测试环境host 配置
app_host: 'http://124.160.35.34:8082'

cms_host: 'http://192.168.3.213'
#新架构测试环境 host
new_app_host: 'http://124.160.35.34:8091/service.do/'

#线上host 配置
#app_host: 'https://service.66ifuel.com'

#66快充用户登陆信息
user_info: '{"phone":"18657738815","password":"d7ef70eea3c962820e0c6b3ae25d465a"}'
#后台登陆信息
cms_info: '{"grant_type":"password","response_type":"code","client_id":"testclient","username":"admin","password":"8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"}'


#66快充用户登陆headers
app_headers: '{
   "Content-Type": "application/json; charset=utf-8"
   }'

cms_headers: '{
   "Content-Type": "application/x-www-form-urlencoded",
   "Connection": "keep-alive",
   "Authorization": ""
  }'


#新架构 app headers
new_app_headers: '{
   "Content-Type": "application/x-www-form-urlencoded",
   "Connection": "keep-alive"
   }'
